// Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from "typeorm";
import { DBConfiguration } from "./Configuration";
import { SettingsEntity } from "./db/Settings.entity";
//autogenerate imports based on resources
import { UsersEntity } from "./db/Users.entity";
import { CardsEntity } from "./db/Cards.entity";
import { SetsEntity } from "./db/Sets.entity";
import { InventoryEntity } from "./db/Inventory.entity";
import { WishlistEntity } from "./db/Wishlist.entity";

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      UsersEntity,
      CardsEntity,
      SetsEntity,
      InventoryEntity,
      WishlistEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      Users: [
        {
          userName: "userName 1",
          password: "password 1",
          email: "email 1",
          id: 80,
        },
        {
          userName: "userName 2",
          password: "password 2",
          email: "email 2",
          id: 15,
        },
        {
          userName: "userName 3",
          password: "password 3",
          email: "email 3",
          id: 11,
        },
        {
          userName: "userName 4",
          password: "password 4",
          email: "email 4",
          id: 88,
        },
        {
          userName: "userName 5",
          password: "password 5",
          email: "email 5",
          id: 67,
        },
      ],
      Cards: [
        {
          cardName: "cardName 1",
          serial: "serial 1",
          type: "type 1",
          rarity: "rarity 1",
          condition: "condition 1",
          imageUrl: "imageUrl 1",
          set: 1,
          id: 82,
        },
        {
          cardName: "cardName 2",
          serial: "serial 2",
          type: "type 2",
          rarity: "rarity 2",
          condition: "condition 2",
          imageUrl: "imageUrl 2",
          set: 2,
          id: 61,
        },
        {
          cardName: "cardName 3",
          serial: "serial 3",
          type: "type 3",
          rarity: "rarity 3",
          condition: "condition 3",
          imageUrl: "imageUrl 3",
          set: 3,
          id: 39,
        },
        {
          cardName: "cardName 4",
          serial: "serial 4",
          type: "type 4",
          rarity: "rarity 4",
          condition: "condition 4",
          imageUrl: "imageUrl 4",
          set: 4,
          id: 74,
        },
        {
          cardName: "cardName 5",
          serial: "serial 5",
          type: "type 5",
          rarity: "rarity 5",
          condition: "condition 5",
          imageUrl: "imageUrl 5",
          set: 5,
          id: 54,
        },
      ],
      Sets: [
        {
          setName: "setName 1",
          releaseDate: "2024-04-02T14:30:45.705Z",
          totalCards: 1,
          id: 79,
        },
        {
          setName: "setName 2",
          releaseDate: "2024-10-09T13:57:59.367Z",
          totalCards: 2,
          id: 85,
        },
        {
          setName: "setName 3",
          releaseDate: "2023-12-04T19:33:44.873Z",
          totalCards: 3,
          id: 65,
        },
        {
          setName: "setName 4",
          releaseDate: "2024-02-14T13:36:20.909Z",
          totalCards: 4,
          id: 100,
        },
        {
          setName: "setName 5",
          releaseDate: "2023-09-17T21:46:37.951Z",
          totalCards: 5,
          id: 19,
        },
      ],
      Inventory: [
        { user: 1, card: 1, dateAdded: "2024-01-06T10:56:40.543Z", id: 58 },
        { user: 2, card: 2, dateAdded: "2025-02-18T22:35:27.396Z", id: 39 },
        { user: 3, card: 3, dateAdded: "2024-04-28T18:56:25.569Z", id: 0 },
        { user: 4, card: 4, dateAdded: "2024-09-02T05:30:24.188Z", id: 50 },
        { user: 5, card: 5, dateAdded: "2025-02-08T07:38:12.713Z", id: 9 },
      ],
      Wishlist: [
        { user: 1, card: 1, dateInserted: "2024-12-23T12:50:16.836Z", id: 26 },
        { user: 2, card: 2, dateInserted: "2023-07-30T19:00:43.960Z", id: 23 },
        { user: 3, card: 3, dateInserted: "2024-05-08T02:09:03.008Z", id: 98 },
        { user: 4, card: 4, dateInserted: "2024-01-16T01:41:20.058Z", id: 100 },
        { user: 5, card: 5, dateInserted: "2023-11-05T17:04:23.581Z", id: 63 },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log("   Seeding database...");
      await this.SeedResource("UsersEntity", data.Users);
      await this.SeedResource("CardsEntity", data.Cards);
      await this.SeedResource("SetsEntity", data.Sets);
      await this.SeedResource("InventoryEntity", data.Inventory);
      await this.SeedResource("WishlistEntity", data.Wishlist);
      await this.SeedResource("SettingsEntity", {
        settingname: "isSeeded",
        settingvalue: "true",
      });
    } else {
      console.log("   Database seeded already!");
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository("SettingsEntity");
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: "isSeeded",
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log("   Seeding table " + resourceName);
    await repo.upsert(resourceData, ["id"]);
  }
}
