//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Customers")
export class CustomersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
customer_id: string;

@Column({nullable: true})
name: string;

@Column({nullable: true})
email: string;


}
