// Source code generated by AppGPT (www.appgpt.tech)

import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  base: "/ab11c2b73/",
  build: {
    outDir: ".outputab11c2b73",
    emptyOutDir: true,
  },
  server: {
    host: true,
    strictPort: true,
    port: 5173,
  },
});
