//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Attendance")
export class AttendanceEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
attendanceId: string;

@Column({nullable: true})
date: string;

@Column({nullable: true})
studentId: string;

@Column({nullable: true})
activityId: string;


}
