//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Orderdetails")
export class OrderdetailsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
orderId: string;

@Column({nullable: true})
productId: string;

@Column({nullable: true})
price: string;

@Column({nullable: true})
sku: string;

@Column({nullable: true})
quantity: string;


}
