//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Orders")
export class OrdersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
orderId: string;

@Column({nullable: true})
customerId: string;

@Column({nullable: true})
amount: string;

@Column({nullable: true})
shippingAddress: string;

@Column({nullable: true})
orderAddress: string;

@Column({nullable: true})
orderEmail: string;

@Column({nullable: true})
orderDate: string;

@Column({nullable: true})
orderStatus: string;


}
