//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Productcategories")
export class ProductcategoriesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
categoryDescription: string;


}
