//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("productCategories")
export class productCategoriesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("text",{nullable: true})
description: string;


}
