//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Products")
export class ProductsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
productId: string;

@Column({nullable: true})
sku: string;

@Column({nullable: true})
name: string;

@Column({nullable: true})
price: string;

@Column({nullable: true})
weight: string;

@Column({nullable: true})
description: string;

@Column({nullable: true})
thumbnail: string;

@Column({nullable: true})
image: string;

@Column({nullable: true})
categoryId: string;

@Column({nullable: true})
createDate: string;

@Column({nullable: true})
stock: string;


}
