//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("vendors")
export class vendorsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("text",{nullable: true})
companyName: string;

@Column("text",{nullable: true})
contactName: string;

@Column("text",{nullable: true})
email: string;

@Column("text",{nullable: true})
password: string;


}
