// in i18nProvider.js
    import { mergeTranslations } from "ra-core";
    import polyglotI18nProvider from "ra-i18n-polyglot";
    import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

    const enResources = { resources: {"Users":{"name":"Users","fields":{"id":"Id","name":"Name","email":"Email","password":"Password","role":"Role"}},"Vendors":{"name":"Vendors","fields":{"id":"Id","companyName":"Company Name","contactName":"Contact Name","email":"Email","password":"Password"}},"Customers":{"name":"Customers","fields":{"id":"Id","email":"Email","password":"Password","name":"Name","billingAddress":"Billing Address","shippingAddress":"Shipping Address","country":"Country","phone":"Phone"}},"Inventory":{"name":"Inventory","fields":{"id":"Id","productId":"Product Id","quantity":"Quantity","vendorId":"Vendor Id","lowStockThreshold":"Low Stock Threshold"}},"Products":{"name":"Products","fields":{"id":"Id","vendorId":"Vendor Id","name":"Name","price":"Price","weight":"Weight","description":"Description","thumbnail":"Thumbnail","image":"Image","category":"Category","createdDate":"Created Date"}},"ProductCategories":{"name":"Product Categories","fields":{"id":"Id","description":"Description"}},"Discounts":{"name":"Discounts","fields":{"id":"Id","productId":"Product Id","discountName":"Discount Name","description":"Description","discountAmount":"Discount Amount","discountPercent":"Discount Percent"}},"ShoppingCarts":{"name":"Shopping Carts","fields":{"id":"Id","customerId":"Customer Id","productId":"Product Id","price":"Price","quantity":"Quantity"}},"Orders":{"name":"Orders","fields":{"id":"Id","customerId":"Customer Id","totalAmount":"Total Amount","vat":"Vat","productTotalAmount":"Product Total Amount","shippingCost":"Shipping Cost","shippingAddress":"Shipping Address","orderAddress":"Order Address","orderEmail":"Order Email","orderDate":"Order Date","orderStatus":"Order Status","trackingNo":"Tracking No"}},"OrderDetails":{"name":"Order Details","fields":{"id":"Id","orderId":"Order Id","productId":"Product Id","price":"Price","quantity":"Quantity"}},"Payments":{"name":"Payments","fields":{"id":"Id","orderId":"Order Id","amount":"Amount","paymentMethod":"Payment Method","paymentDate":"Payment Date","paymentStatus":"Payment Status"}},"Reviews":{"name":"Reviews","fields":{"id":"Id","productId":"Product Id","customerId":"Customer Id","vendorId":"Vendor Id","rating":"Rating","reviewDetails":"Review Details","date":"Date"}},"SupportTickets":{"name":"Support Tickets","fields":{"id":"Id","userId":"User Id","customerId":"Customer Id","description":"Description","status":"Status","creationDate":"Creation Date","lastUpdateDate":"Last Update Date"}}}};
const frResources = { resources: {"Users":{"name":"Users (fr)","fields":{"id":"Id (fr)","name":"Name (fr)","email":"Email (fr)","password":"Password (fr)","role":"Role (fr)"}},"Vendors":{"name":"Vendors (fr)","fields":{"id":"Id (fr)","companyName":"Company Name (fr)","contactName":"Contact Name (fr)","email":"Email (fr)","password":"Password (fr)"}},"Customers":{"name":"Customers (fr)","fields":{"id":"Id (fr)","email":"Email (fr)","password":"Password (fr)","name":"Name (fr)","billingAddress":"Billing Address (fr)","shippingAddress":"Shipping Address (fr)","country":"Country (fr)","phone":"Phone (fr)"}},"Inventory":{"name":"Inventory (fr)","fields":{"id":"Id (fr)","productId":"Product Id (fr)","quantity":"Quantity (fr)","vendorId":"Vendor Id (fr)","lowStockThreshold":"Low Stock Threshold (fr)"}},"Products":{"name":"Products (fr)","fields":{"id":"Id (fr)","vendorId":"Vendor Id (fr)","name":"Name (fr)","price":"Price (fr)","weight":"Weight (fr)","description":"Description (fr)","thumbnail":"Thumbnail (fr)","image":"Image (fr)","category":"Category (fr)","createdDate":"Created Date (fr)"}},"ProductCategories":{"name":"Product Categories (fr)","fields":{"id":"Id (fr)","description":"Description (fr)"}},"Discounts":{"name":"Discounts (fr)","fields":{"id":"Id (fr)","productId":"Product Id (fr)","discountName":"Discount Name (fr)","description":"Description (fr)","discountAmount":"Discount Amount (fr)","discountPercent":"Discount Percent (fr)"}},"ShoppingCarts":{"name":"Shopping Carts (fr)","fields":{"id":"Id (fr)","customerId":"Customer Id (fr)","productId":"Product Id (fr)","price":"Price (fr)","quantity":"Quantity (fr)"}},"Orders":{"name":"Orders (fr)","fields":{"id":"Id (fr)","customerId":"Customer Id (fr)","totalAmount":"Total Amount (fr)","vat":"Vat (fr)","productTotalAmount":"Product Total Amount (fr)","shippingCost":"Shipping Cost (fr)","shippingAddress":"Shipping Address (fr)","orderAddress":"Order Address (fr)","orderEmail":"Order Email (fr)","orderDate":"Order Date (fr)","orderStatus":"Order Status (fr)","trackingNo":"Tracking No (fr)"}},"OrderDetails":{"name":"Order Details (fr)","fields":{"id":"Id (fr)","orderId":"Order Id (fr)","productId":"Product Id (fr)","price":"Price (fr)","quantity":"Quantity (fr)"}},"Payments":{"name":"Payments (fr)","fields":{"id":"Id (fr)","orderId":"Order Id (fr)","amount":"Amount (fr)","paymentMethod":"Payment Method (fr)","paymentDate":"Payment Date (fr)","paymentStatus":"Payment Status (fr)"}},"Reviews":{"name":"Reviews (fr)","fields":{"id":"Id (fr)","productId":"Product Id (fr)","customerId":"Customer Id (fr)","vendorId":"Vendor Id (fr)","rating":"Rating (fr)","reviewDetails":"Review Details (fr)","date":"Date (fr)"}},"SupportTickets":{"name":"Support Tickets (fr)","fields":{"id":"Id (fr)","userId":"User Id (fr)","customerId":"Customer Id (fr)","description":"Description (fr)","status":"Status (fr)","creationDate":"Creation Date (fr)","lastUpdateDate":"Last Update Date (fr)"}}}};


    const en = mergeTranslations(enOriginal,enResources);
const fr = mergeTranslations(frOriginal,frResources);

    const translations = { en, fr};
    export const i18nProvider = polyglotI18nProvider(
      (locale) => translations[locale],
      "en", //default locale
      [{"locale":"en","name":"English"},{"locale":"fr","name":"Français"}]
    );
    