// in i18nProvider.js
    import { mergeTranslations } from "ra-core";
    import polyglotI18nProvider from "ra-i18n-polyglot";
    import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

    const enResources = { resources: {"users":{"name":"Users","fields":{"id":"Id","name":"Name","email":"Email","password":"Password","role":"Role"}},"vendors":{"name":"Vendors","fields":{"id":"Id","companyName":"Company Name","contactName":"Contact Name","email":"Email","password":"Password"}},"customers":{"name":"Customers","fields":{"id":"Id","email":"Email","password":"Password","name":"Name","billingAddress":"Billing Address","shippingAddress":"Shipping Address","country":"Country","phone":"Phone"}},"inventory":{"name":"Inventory","fields":{"id":"Id","productId":"Product Id","quantity":"Quantity","vendorId":"Vendor Id","lowStockThreshold":"Low Stock Threshold"}},"products":{"name":"Products","fields":{"id":"Id","vendorId":"Vendor Id","name":"Name","price":"Price","weight":"Weight","description":"Description","thumbnail":"Thumbnail","image":"Image","category":"Category","createdDate":"Created Date"}},"productCategories":{"name":"Product Categories","fields":{"id":"Id","description":"Description"}},"discounts":{"name":"Discounts","fields":{"id":"Id","product_id":"Product_id","discountName":"Discount Name","description":"Description","discountAmount":"Discount Amount","discountPercent":"Discount Percent"}},"shoppingCarts":{"name":"Shopping Carts","fields":{"id":"Id","customerId":"Customer Id","productId":"Product Id","price":"Price","quantity":"Quantity"}},"orders":{"name":"Orders","fields":{"id":"Id","customerId":"Customer Id","totalAmount":"Total Amount","vat":"Vat","productTotalAmount":"Product Total Amount","shippingCost":"Shipping Cost","shippingAddress":"Shipping Address","orderAddress":"Order Address","orderEmail":"Order Email","orderDate":"Order Date","orderStatus":"Order Status","trackingNo":"Tracking No"}},"orderDetails":{"name":"Order Details","fields":{"id":"Id","orderId":"Order Id","productId":"Product Id","price":"Price","quantity":"Quantity"}},"payments":{"name":"Payments","fields":{"id":"Id","orderId":"Order Id","amount":"Amount","paymentMethod":"Payment Method","paymentDate":"Payment Date","paymentStatus":"Payment Status"}},"reviews":{"name":"Reviews","fields":{"id":"Id","productId":"Product Id","customerId":"Customer Id","vendorId":"Vendor Id","rating":"Rating","reviewDetails":"Review Details","date":"Date"}},"supportTickets":{"name":"Support Tickets","fields":{"id":"Id","userId":"User Id","customerId":"Customer Id","description":"Description","status":"Status","creationDate":"Creation Date","resolutionDate":"Resolution Date"}}}};
const frResources = { resources: {"users":{"name":"Users (fr)","fields":{"id":"Id (fr)","name":"Name (fr)","email":"Email (fr)","password":"Password (fr)","role":"Role (fr)"}},"vendors":{"name":"Vendors (fr)","fields":{"id":"Id (fr)","companyName":"Company Name (fr)","contactName":"Contact Name (fr)","email":"Email (fr)","password":"Password (fr)"}},"customers":{"name":"Customers (fr)","fields":{"id":"Id (fr)","email":"Email (fr)","password":"Password (fr)","name":"Name (fr)","billingAddress":"Billing Address (fr)","shippingAddress":"Shipping Address (fr)","country":"Country (fr)","phone":"Phone (fr)"}},"inventory":{"name":"Inventory (fr)","fields":{"id":"Id (fr)","productId":"Product Id (fr)","quantity":"Quantity (fr)","vendorId":"Vendor Id (fr)","lowStockThreshold":"Low Stock Threshold (fr)"}},"products":{"name":"Products (fr)","fields":{"id":"Id (fr)","vendorId":"Vendor Id (fr)","name":"Name (fr)","price":"Price (fr)","weight":"Weight (fr)","description":"Description (fr)","thumbnail":"Thumbnail (fr)","image":"Image (fr)","category":"Category (fr)","createdDate":"Created Date (fr)"}},"productCategories":{"name":"Product Categories (fr)","fields":{"id":"Id (fr)","description":"Description (fr)"}},"discounts":{"name":"Discounts (fr)","fields":{"id":"Id (fr)","product_id":"Product_id (fr)","discountName":"Discount Name (fr)","description":"Description (fr)","discountAmount":"Discount Amount (fr)","discountPercent":"Discount Percent (fr)"}},"shoppingCarts":{"name":"Shopping Carts (fr)","fields":{"id":"Id (fr)","customerId":"Customer Id (fr)","productId":"Product Id (fr)","price":"Price (fr)","quantity":"Quantity (fr)"}},"orders":{"name":"Orders (fr)","fields":{"id":"Id (fr)","customerId":"Customer Id (fr)","totalAmount":"Total Amount (fr)","vat":"Vat (fr)","productTotalAmount":"Product Total Amount (fr)","shippingCost":"Shipping Cost (fr)","shippingAddress":"Shipping Address (fr)","orderAddress":"Order Address (fr)","orderEmail":"Order Email (fr)","orderDate":"Order Date (fr)","orderStatus":"Order Status (fr)","trackingNo":"Tracking No (fr)"}},"orderDetails":{"name":"Order Details (fr)","fields":{"id":"Id (fr)","orderId":"Order Id (fr)","productId":"Product Id (fr)","price":"Price (fr)","quantity":"Quantity (fr)"}},"payments":{"name":"Payments (fr)","fields":{"id":"Id (fr)","orderId":"Order Id (fr)","amount":"Amount (fr)","paymentMethod":"Payment Method (fr)","paymentDate":"Payment Date (fr)","paymentStatus":"Payment Status (fr)"}},"reviews":{"name":"Reviews (fr)","fields":{"id":"Id (fr)","productId":"Product Id (fr)","customerId":"Customer Id (fr)","vendorId":"Vendor Id (fr)","rating":"Rating (fr)","reviewDetails":"Review Details (fr)","date":"Date (fr)"}},"supportTickets":{"name":"Support Tickets (fr)","fields":{"id":"Id (fr)","userId":"User Id (fr)","customerId":"Customer Id (fr)","description":"Description (fr)","status":"Status (fr)","creationDate":"Creation Date (fr)","resolutionDate":"Resolution Date (fr)"}}}};


    const en = mergeTranslations(enOriginal,enResources);
const fr = mergeTranslations(frOriginal,frResources);

    const translations = { en, fr};
    export const i18nProvider = polyglotI18nProvider(
      (locale) => translations[locale],
      "en", //default locale
      [{"locale":"en","name":"English"},{"locale":"fr","name":"Français"}]
    );
    